version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bd_gestion_semana10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gestion_bdatos
      POSTGRES_USER: erick
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
